[General]
network = TracerouteTestNetwork


#simulation control parameters
sim-time-limit = 1200s 
repeat = 5


# RNG initialization
num-rngs = 8
seed-0-mt = 1000   # left specifically unused
seed-1-mt = 2000   # demiurge
seed-2-mt = 3000   # numen
seed-3-mt = 4000   # applications
seed-4-mt = 5000   # forwarding
seed-5-mt = 6000   # wired
seed-6-mt = 7000   # wireless
seed-7-mt = 8000   # mobility


# RNG use
simtime-resolution = ms
**.demiurge.rng-0 = 1
**.numen.rng-0 = 2
**.app[*].rng-0 = 3
**.fwd.rng-0 = 4
**.wired[*].rng-0 = 5
**.wireless[*].rng-0 = 6
**.mobility.rng-0 = 7


# results location
result-dir = results/
output-vector-file = "${resultdir}/${inifile}-${configname}-${runnumber}.vec"
output-scalar-file = "${resultdir}/${inifile}-${configname}-${runnumber}.sca"


# statistic collection
**.vector-recording = true
**.scalar-recording = true
**.statistic-recording = true


# log events
record-eventlog = false
eventlog-file = "${resultdir}/${inifile}-${configname}-${runnumber}.elog"


[Config Traceroute-3-content]

# General Forwarder settings
**.**.forwarder = "RFC8569WithPingForwarder"

# Content Server 1 settings
**.contentServer1.numApps = 1
**.contentServer1.app[0].typename = "ContentHostApp"
**.contentServer1.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer1.app[0].dataNamePrefix = "sptm"
**.contentServer1.app[0].segmentSize = 1000byte
**.contentServer1.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer1.app[0].cacheTime = 2h


# Content Server 2 settings
**.contentServer2.numApps = 1
**.contentServer2.app[0].typename = "ContentHostApp"
**.contentServer2.app[0].hostedPrefixNames = "ccnx://relativity.com/"
**.contentServer2.app[0].dataNamePrefix = "rltv"
**.contentServer2.app[0].segmentSize = 1000byte
**.contentServer2.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer2.app[0].cacheTime = 2h

# Content Server 3 settings
**.contentServer3.numApps = 1
**.contentServer3.app[0].typename = "ContentHostApp"
**.contentServer3.app[0].hostedPrefixNames = "ccnx://uni-bremen.de/"
**.contentServer3.app[0].dataNamePrefix = "unib"
**.contentServer3.app[0].segmentSize = 1000byte
**.contentServer3.app[0].numSegmentsPerFile = intuniform(5,20)
**.contentServer3.app[0].cacheTime = 2h


# Wired Access Router Settings
**.accessRouter1.accessRouterNumWiredTransports = 4
**.accessRouter2.accessRouterNumWiredTransports = 4
**.accessRouter3.accessRouterNumWiredTransports = 4


# Wired Node settings
**.wiredNode*.numApps = 2

# Content Download
**.wiredNode*.app[0].typename = "ContentDownloadApp"
**.wiredNode*.app[0].interContentDownloadInterval = uniform(100.0s, 150.0s)
**.wiredNode*.app[0].interestRetransmitTimeout = 120s
**.wiredNode*.app[0].nextFileSuffix = intuniform(0, 99)
**.wiredNode*.app[0].maxHopsAllowed = 9 #only 7 nodes to hop, but reflexive forwarding setup deducts hops to often, out of scope for traceroute project

# Traceroute
**.wiredNode*.app[1].typename = "TraceRouteApp"
**.wiredNode*.app[1].startOffset = 150s
**.wiredNode*.app[1].interestRetransmitTimeout = 120s
**.wiredNode*.app[1].maxHopsAllowed = 1
**.wiredNode*.app[1].totalHopLimit = 12

# Setup for requested namespaces
**.wiredNode1.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[0].dataNamePrefix = "sptm"

**.wiredNode1.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[1].dataNamePrefix = "sptm"

**.wiredNode4.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[0].dataNamePrefix = "sptm"

**.wiredNode4.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[1].dataNamePrefix = "sptm"

**.wiredNode7.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[0].dataNamePrefix = "sptm"

**.wiredNode7.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[1].dataNamePrefix = "sptm"

**.wiredNode2.app[0].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode2.app[0].dataNamePrefix = "rltv"

**.wiredNode2.app[1].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode2.app[1].dataNamePrefix = "rltv"

**.wiredNode5.app[0].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode5.app[0].dataNamePrefix = "rltv"

**.wiredNode5.app[1].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode5.app[1].dataNamePrefix = "rltv"

**.wiredNode8.app[0].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode8.app[0].dataNamePrefix = "rltv"

**.wiredNode8.app[1].requestedPrefixNames = "ccnx://relativity.com/"
**.wiredNode8.app[1].dataNamePrefix = "rltv"

**.wiredNode3.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode3.app[0].dataNamePrefix = "unib"

**.wiredNode3.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode3.app[1].dataNamePrefix = "unib"

**.wiredNode6.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode6.app[0].dataNamePrefix = "unib"

**.wiredNode6.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode6.app[1].dataNamePrefix = "unib"

**.wiredNode9.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode9.app[0].dataNamePrefix = "unib"

**.wiredNode9.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode9.app[1].dataNamePrefix = "unib"

# Core Router settings
**.coreRouter1.coreRouterNumWiredTransports = 3
**.coreRouter2.coreRouterNumWiredTransports = 4
**.coreRouter3.coreRouterNumWiredTransports = 2
**.coreRouter4.coreRouterNumWiredTransports = 4
**.coreRouter5.coreRouterNumWiredTransports = 4
**.coreRouter6.coreRouterNumWiredTransports = 3
**.coreRouter7.coreRouterNumWiredTransports = 2
**.coreRouter8.coreRouterNumWiredTransports = 2
**.coreRouter9.coreRouterNumWiredTransports = 3
**.coreRouter10.coreRouterNumWiredTransports = 3
**.coreRouter11.coreRouterNumWiredTransports = 2
**.coreRouter12.coreRouterNumWiredTransports = 2


# General Mobility settings
**.constraintAreaMinX = 0m
**.constraintAreaMinY = 0m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxX = 400m
**.constraintAreaMaxY = 400m
**.constraintAreaMaxZ = 0m
**.updateInterval = 1s
**.initFromDisplayString = true

[Config Traceroute-2-content]

# General Forwarder settings
**.**.forwarder = "RFC8569WithPingForwarder"

# Content Server 1 settings
**.contentServer1.numApps = 1
**.contentServer1.app[0].typename = "ContentHostApp"
**.contentServer1.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer1.app[0].dataNamePrefix = "sptm"
**.contentServer1.app[0].segmentSize = 1000byte
**.contentServer1.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer1.app[0].cacheTime = 2h


# Content Server 2 settings
**.contentServer2.numApps = 1
**.contentServer2.app[0].typename = "ContentHostApp"
**.contentServer2.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer2.app[0].dataNamePrefix = "rltv"
**.contentServer2.app[0].segmentSize = 1000byte
**.contentServer2.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer2.app[0].cacheTime = 2h

# Content Server 3 settings
**.contentServer3.numApps = 1
**.contentServer3.app[0].typename = "ContentHostApp"
**.contentServer3.app[0].hostedPrefixNames = "ccnx://uni-bremen.de/"
**.contentServer3.app[0].dataNamePrefix = "unib"
**.contentServer3.app[0].segmentSize = 1000byte
**.contentServer3.app[0].numSegmentsPerFile = intuniform(5,20)
**.contentServer3.app[0].cacheTime = 2h


# Wired Access Router Settings
**.accessRouter1.accessRouterNumWiredTransports = 4
**.accessRouter2.accessRouterNumWiredTransports = 4
**.accessRouter3.accessRouterNumWiredTransports = 4


# Wired Node settings
**.wiredNode*.numApps = 2

# Content Download
**.wiredNode*.app[0].typename = "ContentDownloadApp"
**.wiredNode*.app[0].interContentDownloadInterval = uniform(100.0s, 150.0s)
**.wiredNode*.app[0].interestRetransmitTimeout = 120s
**.wiredNode*.app[0].nextFileSuffix = intuniform(0, 99)
**.wiredNode*.app[0].maxHopsAllowed = 9 #only 7 nodes to hop, but reflexive forwarding setup deducts hops to often, out of scope for traceroute project

# Traceroute
**.wiredNode*.app[1].typename = "TraceRouteApp"
**.wiredNode*.app[1].startOffset = 150s
**.wiredNode*.app[1].interestRetransmitTimeout = 120s
**.wiredNode*.app[1].maxHopsAllowed = 1
**.wiredNode*.app[1].totalHopLimit = 12

# Setup for requested namespaces
**.wiredNode1.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[0].dataNamePrefix = "sptm"

**.wiredNode1.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[1].dataNamePrefix = "sptm"

**.wiredNode4.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[0].dataNamePrefix = "sptm"

**.wiredNode4.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[1].dataNamePrefix = "sptm"

**.wiredNode7.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[0].dataNamePrefix = "sptm"

**.wiredNode7.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[1].dataNamePrefix = "sptm"

**.wiredNode2.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode2.app[0].dataNamePrefix = "sptm"

**.wiredNode2.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode2.app[1].dataNamePrefix = "sptm"

**.wiredNode5.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode5.app[0].dataNamePrefix = "sptm"

**.wiredNode5.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode5.app[1].dataNamePrefix = "sptm"

**.wiredNode8.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode8.app[0].dataNamePrefix = "unib"

**.wiredNode8.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode8.app[1].dataNamePrefix = "unib"

**.wiredNode3.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode3.app[0].dataNamePrefix = "unib"

**.wiredNode3.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode3.app[1].dataNamePrefix = "unib"

**.wiredNode6.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode6.app[0].dataNamePrefix = "unib"

**.wiredNode6.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode6.app[1].dataNamePrefix = "unib"

**.wiredNode9.app[0].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode9.app[0].dataNamePrefix = "unib"

**.wiredNode9.app[1].requestedPrefixNames = "ccnx://uni-bremen.de/"
**.wiredNode9.app[1].dataNamePrefix = "unib"

# Core Router settings
**.coreRouter1.coreRouterNumWiredTransports = 3
**.coreRouter2.coreRouterNumWiredTransports = 4
**.coreRouter3.coreRouterNumWiredTransports = 2
**.coreRouter4.coreRouterNumWiredTransports = 4
**.coreRouter5.coreRouterNumWiredTransports = 4
**.coreRouter6.coreRouterNumWiredTransports = 3
**.coreRouter7.coreRouterNumWiredTransports = 2
**.coreRouter8.coreRouterNumWiredTransports = 2
**.coreRouter9.coreRouterNumWiredTransports = 3
**.coreRouter10.coreRouterNumWiredTransports = 3
**.coreRouter11.coreRouterNumWiredTransports = 2
**.coreRouter12.coreRouterNumWiredTransports = 2


# General Mobility settings
**.constraintAreaMinX = 0m
**.constraintAreaMinY = 0m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxX = 400m
**.constraintAreaMaxY = 400m
**.constraintAreaMaxZ = 0m
**.updateInterval = 1s
**.initFromDisplayString = true

[Config Traceroute-1-content]

# General Forwarder settings
**.**.forwarder = "RFC8569WithPingForwarder"

# Content Server 1 settings
**.contentServer1.numApps = 1
**.contentServer1.app[0].typename = "ContentHostApp"
**.contentServer1.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer1.app[0].dataNamePrefix = "sptm"
**.contentServer1.app[0].segmentSize = 1000byte
**.contentServer1.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer1.app[0].cacheTime = 2h


# Content Server 2 settings
**.contentServer2.numApps = 1
**.contentServer2.app[0].typename = "ContentHostApp"
**.contentServer2.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer2.app[0].dataNamePrefix = "rltv"
**.contentServer2.app[0].segmentSize = 1000byte
**.contentServer2.app[0].numSegmentsPerFile = intuniform(5, 20)
**.contentServer2.app[0].cacheTime = 2h

# Content Server 3 settings
**.contentServer3.numApps = 1
**.contentServer3.app[0].typename = "ContentHostApp"
**.contentServer3.app[0].hostedPrefixNames = "ccnx://spacetime.com/"
**.contentServer3.app[0].dataNamePrefix = "sptm"
**.contentServer3.app[0].segmentSize = 1000byte
**.contentServer3.app[0].numSegmentsPerFile = intuniform(5,20)
**.contentServer3.app[0].cacheTime = 2h


# Wired Access Router Settings
**.accessRouter1.accessRouterNumWiredTransports = 4
**.accessRouter2.accessRouterNumWiredTransports = 4
**.accessRouter3.accessRouterNumWiredTransports = 4


# Wired Node settings
**.wiredNode*.numApps = 2

# Content Download
**.wiredNode*.app[0].typename = "ContentDownloadApp"
**.wiredNode*.app[0].interContentDownloadInterval = uniform(100.0s, 150.0s)
**.wiredNode*.app[0].interestRetransmitTimeout = 120s
**.wiredNode*.app[0].nextFileSuffix = intuniform(0, 99)
**.wiredNode*.app[0].maxHopsAllowed = 9 #only 7 nodes to hop, but reflexive forwarding setup deducts hops to often, out of scope for traceroute project

# Traceroute
**.wiredNode*.app[1].typename = "TraceRouteApp"
**.wiredNode*.app[1].startOffset = 150s
**.wiredNode*.app[1].interestRetransmitTimeout = 120s
**.wiredNode*.app[1].maxHopsAllowed = 1
**.wiredNode*.app[1].totalHopLimit = 12

# Setup for requested namespaces
**.wiredNode1.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[0].dataNamePrefix = "sptm"

**.wiredNode1.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode1.app[1].dataNamePrefix = "sptm"

**.wiredNode4.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[0].dataNamePrefix = "sptm"

**.wiredNode4.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode4.app[1].dataNamePrefix = "sptm"

**.wiredNode7.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[0].dataNamePrefix = "sptm"

**.wiredNode7.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode7.app[1].dataNamePrefix = "sptm"

**.wiredNode2.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode2.app[0].dataNamePrefix = "sptm"

**.wiredNode2.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode2.app[1].dataNamePrefix = "sptm"

**.wiredNode5.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode5.app[0].dataNamePrefix = "sptm"

**.wiredNode5.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode5.app[1].dataNamePrefix = "sptm"

**.wiredNode8.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode8.app[0].dataNamePrefix = "sptm"

**.wiredNode8.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode8.app[1].dataNamePrefix = "sptm"

**.wiredNode3.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode3.app[0].dataNamePrefix = "sptm"

**.wiredNode3.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode3.app[1].dataNamePrefix = "sptm"

**.wiredNode6.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode6.app[0].dataNamePrefix = "sptm"

**.wiredNode6.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode6.app[1].dataNamePrefix = "sptm"

**.wiredNode9.app[0].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode9.app[0].dataNamePrefix = "sptm"

**.wiredNode9.app[1].requestedPrefixNames = "ccnx://spacetime.com/"
**.wiredNode9.app[1].dataNamePrefix = "sptm"

# Core Router settings
**.coreRouter1.coreRouterNumWiredTransports = 3
**.coreRouter2.coreRouterNumWiredTransports = 4
**.coreRouter3.coreRouterNumWiredTransports = 2
**.coreRouter4.coreRouterNumWiredTransports = 4
**.coreRouter5.coreRouterNumWiredTransports = 4
**.coreRouter6.coreRouterNumWiredTransports = 3
**.coreRouter7.coreRouterNumWiredTransports = 2
**.coreRouter8.coreRouterNumWiredTransports = 2
**.coreRouter9.coreRouterNumWiredTransports = 3
**.coreRouter10.coreRouterNumWiredTransports = 3
**.coreRouter11.coreRouterNumWiredTransports = 2
**.coreRouter12.coreRouterNumWiredTransports = 2


# General Mobility settings
**.constraintAreaMinX = 0m
**.constraintAreaMinY = 0m
**.constraintAreaMinZ = 0m
**.constraintAreaMaxX = 400m
**.constraintAreaMaxY = 400m
**.constraintAreaMaxZ = 0m
**.updateInterval = 1s
**.initFromDisplayString = true